/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAssistenteIaRouteImport } from './routes/_authenticated/assistente-ia'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAutomacoesRouteImport } from './routes/_authenticated/automacoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedEstudosRouteImport } from './routes/_authenticated/estudos'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedComercialAtividadesRouteImport } from './routes/_authenticated/comercial.atividades'
import { Route as AuthenticatedComercialCadenciasRouteImport } from './routes/_authenticated/comercial.cadencias'
import { Route as AuthenticatedComercialContatosRouteImport } from './routes/_authenticated/comercial.contatos'
import { Route as AuthenticatedComercialDashboardRouteImport } from './routes/_authenticated/comercial.dashboard'
import { Route as AuthenticatedComercialEmpresasRouteImport } from './routes/_authenticated/comercial.empresas'
import { Route as AuthenticatedComercialLeadsRouteImport } from './routes/_authenticated/comercial.leads'
import { Route as AuthenticatedComercialMetasRouteImport } from './routes/_authenticated/comercial.metas'
import { Route as AuthenticatedComercialOportunidadesRouteImport } from './routes/_authenticated/comercial.oportunidades'
import { Route as AuthenticatedComercialPipelineRouteImport } from './routes/_authenticated/comercial.pipeline'
import { Route as AuthenticatedConfiguracoesEquipeRouteImport } from './routes/_authenticated/configuracoes.equipe'
import { Route as AuthenticatedMarketingCampanhasRouteImport } from './routes/_authenticated/marketing.campanhas'
import { Route as AuthenticatedMarketingConteudosRouteImport } from './routes/_authenticated/marketing.conteudos'
import { Route as AuthenticatedMarketingDashboardRouteImport } from './routes/_authenticated/marketing.dashboard'
import { Route as AuthenticatedMarketingTrafegoRouteImport } from './routes/_authenticated/marketing.trafego'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistenteIaRoute =
  AuthenticatedAssistenteIaRouteImport.update({
    id: '/assistente-ia',
    path: '/assistente-ia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomacoesRoute = AuthenticatedAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstudosRoute = AuthenticatedEstudosRouteImport.update({
  id: '/estudos',
  path: '/estudos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComercialAtividadesRoute =
  AuthenticatedComercialAtividadesRouteImport.update({
    id: '/comercial/atividades',
    path: '/comercial/atividades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComercialCadenciasRoute =
  AuthenticatedComercialCadenciasRouteImport.update({
    id: '/comercial/cadencias',
    path: '/comercial/cadencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComercialContatosRoute =
  AuthenticatedComercialContatosRouteImport.update({
    id: '/comercial/contatos',
    path: '/comercial/contatos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComercialDashboardRoute =
  AuthenticatedComercialDashboardRouteImport.update({
    id: '/comercial/dashboard',
    path: '/comercial/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComercialEmpresasRoute =
  AuthenticatedComercialEmpresasRouteImport.update({
    id: '/comercial/empresas',
    path: '/comercial/empresas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComercialLeadsRoute =
  AuthenticatedComercialLeadsRouteImport.update({
    id: '/comercial/leads',
    path: '/comercial/leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComercialMetasRoute =
  AuthenticatedComercialMetasRouteImport.update({
    id: '/comercial/metas',
    path: '/comercial/metas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComercialOportunidadesRoute =
  AuthenticatedComercialOportunidadesRouteImport.update({
    id: '/comercial/oportunidades',
    path: '/comercial/oportunidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComercialPipelineRoute =
  AuthenticatedComercialPipelineRouteImport.update({
    id: '/comercial/pipeline',
    path: '/comercial/pipeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesEquipeRoute =
  AuthenticatedConfiguracoesEquipeRouteImport.update({
    id: '/configuracoes/equipe',
    path: '/configuracoes/equipe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingCampanhasRoute =
  AuthenticatedMarketingCampanhasRouteImport.update({
    id: '/marketing/campanhas',
    path: '/marketing/campanhas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingConteudosRoute =
  AuthenticatedMarketingConteudosRouteImport.update({
    id: '/marketing/conteudos',
    path: '/marketing/conteudos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingDashboardRoute =
  AuthenticatedMarketingDashboardRouteImport.update({
    id: '/marketing/dashboard',
    path: '/marketing/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingTrafegoRoute =
  AuthenticatedMarketingTrafegoRouteImport.update({
    id: '/marketing/trafego',
    path: '/marketing/trafego',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/assistente-ia': typeof AuthenticatedAssistenteIaRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/estudos': typeof AuthenticatedEstudosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/comercial/atividades': typeof AuthenticatedComercialAtividadesRoute
  '/comercial/cadencias': typeof AuthenticatedComercialCadenciasRoute
  '/comercial/contatos': typeof AuthenticatedComercialContatosRoute
  '/comercial/dashboard': typeof AuthenticatedComercialDashboardRoute
  '/comercial/empresas': typeof AuthenticatedComercialEmpresasRoute
  '/comercial/leads': typeof AuthenticatedComercialLeadsRoute
  '/comercial/metas': typeof AuthenticatedComercialMetasRoute
  '/comercial/oportunidades': typeof AuthenticatedComercialOportunidadesRoute
  '/comercial/pipeline': typeof AuthenticatedComercialPipelineRoute
  '/configuracoes/equipe': typeof AuthenticatedConfiguracoesEquipeRoute
  '/marketing/campanhas': typeof AuthenticatedMarketingCampanhasRoute
  '/marketing/conteudos': typeof AuthenticatedMarketingConteudosRoute
  '/marketing/dashboard': typeof AuthenticatedMarketingDashboardRoute
  '/marketing/trafego': typeof AuthenticatedMarketingTrafegoRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/assistente-ia': typeof AuthenticatedAssistenteIaRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/estudos': typeof AuthenticatedEstudosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/': typeof AuthenticatedIndexRoute
  '/comercial/atividades': typeof AuthenticatedComercialAtividadesRoute
  '/comercial/cadencias': typeof AuthenticatedComercialCadenciasRoute
  '/comercial/contatos': typeof AuthenticatedComercialContatosRoute
  '/comercial/dashboard': typeof AuthenticatedComercialDashboardRoute
  '/comercial/empresas': typeof AuthenticatedComercialEmpresasRoute
  '/comercial/leads': typeof AuthenticatedComercialLeadsRoute
  '/comercial/metas': typeof AuthenticatedComercialMetasRoute
  '/comercial/oportunidades': typeof AuthenticatedComercialOportunidadesRoute
  '/comercial/pipeline': typeof AuthenticatedComercialPipelineRoute
  '/configuracoes/equipe': typeof AuthenticatedConfiguracoesEquipeRoute
  '/marketing/campanhas': typeof AuthenticatedMarketingCampanhasRoute
  '/marketing/conteudos': typeof AuthenticatedMarketingConteudosRoute
  '/marketing/dashboard': typeof AuthenticatedMarketingDashboardRoute
  '/marketing/trafego': typeof AuthenticatedMarketingTrafegoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assistente-ia': typeof AuthenticatedAssistenteIaRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/automacoes': typeof AuthenticatedAutomacoesRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/estudos': typeof AuthenticatedEstudosRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/comercial/atividades': typeof AuthenticatedComercialAtividadesRoute
  '/_authenticated/comercial/cadencias': typeof AuthenticatedComercialCadenciasRoute
  '/_authenticated/comercial/contatos': typeof AuthenticatedComercialContatosRoute
  '/_authenticated/comercial/dashboard': typeof AuthenticatedComercialDashboardRoute
  '/_authenticated/comercial/empresas': typeof AuthenticatedComercialEmpresasRoute
  '/_authenticated/comercial/leads': typeof AuthenticatedComercialLeadsRoute
  '/_authenticated/comercial/metas': typeof AuthenticatedComercialMetasRoute
  '/_authenticated/comercial/oportunidades': typeof AuthenticatedComercialOportunidadesRoute
  '/_authenticated/comercial/pipeline': typeof AuthenticatedComercialPipelineRoute
  '/_authenticated/configuracoes/equipe': typeof AuthenticatedConfiguracoesEquipeRoute
  '/_authenticated/marketing/campanhas': typeof AuthenticatedMarketingCampanhasRoute
  '/_authenticated/marketing/conteudos': typeof AuthenticatedMarketingConteudosRoute
  '/_authenticated/marketing/dashboard': typeof AuthenticatedMarketingDashboardRoute
  '/_authenticated/marketing/trafego': typeof AuthenticatedMarketingTrafegoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assistente-ia'
    | '/auditoria'
    | '/automacoes'
    | '/clientes'
    | '/estudos'
    | '/financeiro'
    | '/perfil'
    | '/relatorios'
    | '/comercial/atividades'
    | '/comercial/cadencias'
    | '/comercial/contatos'
    | '/comercial/dashboard'
    | '/comercial/empresas'
    | '/comercial/leads'
    | '/comercial/metas'
    | '/comercial/oportunidades'
    | '/comercial/pipeline'
    | '/configuracoes/equipe'
    | '/marketing/campanhas'
    | '/marketing/conteudos'
    | '/marketing/dashboard'
    | '/marketing/trafego'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/assistente-ia'
    | '/auditoria'
    | '/automacoes'
    | '/clientes'
    | '/estudos'
    | '/financeiro'
    | '/perfil'
    | '/relatorios'
    | '/'
    | '/comercial/atividades'
    | '/comercial/cadencias'
    | '/comercial/contatos'
    | '/comercial/dashboard'
    | '/comercial/empresas'
    | '/comercial/leads'
    | '/comercial/metas'
    | '/comercial/oportunidades'
    | '/comercial/pipeline'
    | '/configuracoes/equipe'
    | '/marketing/campanhas'
    | '/marketing/conteudos'
    | '/marketing/dashboard'
    | '/marketing/trafego'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assistente-ia'
    | '/_authenticated/auditoria'
    | '/_authenticated/automacoes'
    | '/_authenticated/clientes'
    | '/_authenticated/estudos'
    | '/_authenticated/financeiro'
    | '/_authenticated/perfil'
    | '/_authenticated/relatorios'
    | '/_authenticated/'
    | '/_authenticated/comercial/atividades'
    | '/_authenticated/comercial/cadencias'
    | '/_authenticated/comercial/contatos'
    | '/_authenticated/comercial/dashboard'
    | '/_authenticated/comercial/empresas'
    | '/_authenticated/comercial/leads'
    | '/_authenticated/comercial/metas'
    | '/_authenticated/comercial/oportunidades'
    | '/_authenticated/comercial/pipeline'
    | '/_authenticated/configuracoes/equipe'
    | '/_authenticated/marketing/campanhas'
    | '/_authenticated/marketing/conteudos'
    | '/_authenticated/marketing/dashboard'
    | '/_authenticated/marketing/trafego'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistente-ia': {
      id: '/_authenticated/assistente-ia'
      path: '/assistente-ia'
      fullPath: '/assistente-ia'
      preLoaderRoute: typeof AuthenticatedAssistenteIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automacoes': {
      id: '/_authenticated/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AuthenticatedAutomacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudos': {
      id: '/_authenticated/estudos'
      path: '/estudos'
      fullPath: '/estudos'
      preLoaderRoute: typeof AuthenticatedEstudosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comercial/atividades': {
      id: '/_authenticated/comercial/atividades'
      path: '/comercial/atividades'
      fullPath: '/comercial/atividades'
      preLoaderRoute: typeof AuthenticatedComercialAtividadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comercial/cadencias': {
      id: '/_authenticated/comercial/cadencias'
      path: '/comercial/cadencias'
      fullPath: '/comercial/cadencias'
      preLoaderRoute: typeof AuthenticatedComercialCadenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comercial/contatos': {
      id: '/_authenticated/comercial/contatos'
      path: '/comercial/contatos'
      fullPath: '/comercial/contatos'
      preLoaderRoute: typeof AuthenticatedComercialContatosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comercial/dashboard': {
      id: '/_authenticated/comercial/dashboard'
      path: '/comercial/dashboard'
      fullPath: '/comercial/dashboard'
      preLoaderRoute: typeof AuthenticatedComercialDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comercial/empresas': {
      id: '/_authenticated/comercial/empresas'
      path: '/comercial/empresas'
      fullPath: '/comercial/empresas'
      preLoaderRoute: typeof AuthenticatedComercialEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comercial/leads': {
      id: '/_authenticated/comercial/leads'
      path: '/comercial/leads'
      fullPath: '/comercial/leads'
      preLoaderRoute: typeof AuthenticatedComercialLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comercial/metas': {
      id: '/_authenticated/comercial/metas'
      path: '/comercial/metas'
      fullPath: '/comercial/metas'
      preLoaderRoute: typeof AuthenticatedComercialMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comercial/oportunidades': {
      id: '/_authenticated/comercial/oportunidades'
      path: '/comercial/oportunidades'
      fullPath: '/comercial/oportunidades'
      preLoaderRoute: typeof AuthenticatedComercialOportunidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comercial/pipeline': {
      id: '/_authenticated/comercial/pipeline'
      path: '/comercial/pipeline'
      fullPath: '/comercial/pipeline'
      preLoaderRoute: typeof AuthenticatedComercialPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/equipe': {
      id: '/_authenticated/configuracoes/equipe'
      path: '/configuracoes/equipe'
      fullPath: '/configuracoes/equipe'
      preLoaderRoute: typeof AuthenticatedConfiguracoesEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing/campanhas': {
      id: '/_authenticated/marketing/campanhas'
      path: '/marketing/campanhas'
      fullPath: '/marketing/campanhas'
      preLoaderRoute: typeof AuthenticatedMarketingCampanhasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing/conteudos': {
      id: '/_authenticated/marketing/conteudos'
      path: '/marketing/conteudos'
      fullPath: '/marketing/conteudos'
      preLoaderRoute: typeof AuthenticatedMarketingConteudosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing/dashboard': {
      id: '/_authenticated/marketing/dashboard'
      path: '/marketing/dashboard'
      fullPath: '/marketing/dashboard'
      preLoaderRoute: typeof AuthenticatedMarketingDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing/trafego': {
      id: '/_authenticated/marketing/trafego'
      path: '/marketing/trafego'
      fullPath: '/marketing/trafego'
      preLoaderRoute: typeof AuthenticatedMarketingTrafegoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistenteIaRoute: typeof AuthenticatedAssistenteIaRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedAutomacoesRoute: typeof AuthenticatedAutomacoesRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedEstudosRoute: typeof AuthenticatedEstudosRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedComercialAtividadesRoute: typeof AuthenticatedComercialAtividadesRoute
  AuthenticatedComercialCadenciasRoute: typeof AuthenticatedComercialCadenciasRoute
  AuthenticatedComercialContatosRoute: typeof AuthenticatedComercialContatosRoute
  AuthenticatedComercialDashboardRoute: typeof AuthenticatedComercialDashboardRoute
  AuthenticatedComercialEmpresasRoute: typeof AuthenticatedComercialEmpresasRoute
  AuthenticatedComercialLeadsRoute: typeof AuthenticatedComercialLeadsRoute
  AuthenticatedComercialMetasRoute: typeof AuthenticatedComercialMetasRoute
  AuthenticatedComercialOportunidadesRoute: typeof AuthenticatedComercialOportunidadesRoute
  AuthenticatedComercialPipelineRoute: typeof AuthenticatedComercialPipelineRoute
  AuthenticatedConfiguracoesEquipeRoute: typeof AuthenticatedConfiguracoesEquipeRoute
  AuthenticatedMarketingCampanhasRoute: typeof AuthenticatedMarketingCampanhasRoute
  AuthenticatedMarketingConteudosRoute: typeof AuthenticatedMarketingConteudosRoute
  AuthenticatedMarketingDashboardRoute: typeof AuthenticatedMarketingDashboardRoute
  AuthenticatedMarketingTrafegoRoute: typeof AuthenticatedMarketingTrafegoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistenteIaRoute: AuthenticatedAssistenteIaRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedAutomacoesRoute: AuthenticatedAutomacoesRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedEstudosRoute: AuthenticatedEstudosRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedComercialAtividadesRoute: AuthenticatedComercialAtividadesRoute,
  AuthenticatedComercialCadenciasRoute: AuthenticatedComercialCadenciasRoute,
  AuthenticatedComercialContatosRoute: AuthenticatedComercialContatosRoute,
  AuthenticatedComercialDashboardRoute: AuthenticatedComercialDashboardRoute,
  AuthenticatedComercialEmpresasRoute: AuthenticatedComercialEmpresasRoute,
  AuthenticatedComercialLeadsRoute: AuthenticatedComercialLeadsRoute,
  AuthenticatedComercialMetasRoute: AuthenticatedComercialMetasRoute,
  AuthenticatedComercialOportunidadesRoute:
    AuthenticatedComercialOportunidadesRoute,
  AuthenticatedComercialPipelineRoute: AuthenticatedComercialPipelineRoute,
  AuthenticatedConfiguracoesEquipeRoute: AuthenticatedConfiguracoesEquipeRoute,
  AuthenticatedMarketingCampanhasRoute: AuthenticatedMarketingCampanhasRoute,
  AuthenticatedMarketingConteudosRoute: AuthenticatedMarketingConteudosRoute,
  AuthenticatedMarketingDashboardRoute: AuthenticatedMarketingDashboardRoute,
  AuthenticatedMarketingTrafegoRoute: AuthenticatedMarketingTrafegoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
